name: typescript-action
description: Template of TypeScript Action

inputs:
  sha:
    description: target commit sha
    required: true
    default: ${{ github.sha }}

runs:
  using: 'node16'
  main: 'dist/index.js'
