name: argocd-status-action
description: Wait for Argo CD in GitHub Actions

inputs:
  sha:
    description: target commit sha
    required: true
    default: ${{ github.sha }}

runs:
  using: 'node16'
  main: 'dist/index.js'
