name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          path: e2e/fixture-checkout
      - run: make -C e2e setup-fixture-branch
      - run: make -C e2e cluster
      - run: make -C e2e deploy-argocd
      - run: make -C e2e deploy-app1
      - uses: ./
      - run: make -C e2e deploy-app2
      - uses: ./
      - run: make -C e2e deploy-app3
      - uses: ./
      - run: make -C e2e logs-argocd
        if: always()
      - run: make -C e2e delete-fixture-branch
        if: always()

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint --fix
      - run: yarn format
      - uses: int128/update-generated-files-action@9cf17834a8b281b48b8523a3ba36d178ed71e0f4 # v2.38.0
